services:
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    restart: unless-stopped
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # [설정파일]
#      - ./volumes/prometheus:/prometheus          # [데이터 볼륨]
##    depends_on:
##      - backend1
##      - backend2
##      - backend3
#    networks:
#      - prod_server
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    depends_on:
#      - prometheus
#    volumes:
#      - ./volumes/grafana:/var/lib/grafana  # [데이터 볼륨]
#    networks:
#      - prod_server


  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # ★ 추가!!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/es01data:/usr/share/elasticsearch/data
    networks:
      - prod_server

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # ★ 추가!!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9202:9200"
      - "9302:9300"
    volumes:
      - ./volumes/es02data:/usr/share/elasticsearch/data
    networks:
      - prod_server

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # ★ 추가!!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9203:9200"
      - "9303:9300"
    volumes:
      - ./volumes/es03data:/usr/share/elasticsearch/data
    networks:
      - prod_server

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]
      - SERVER_SSL_ENABLED=false
    ports:
      - "5601:5601"
    volumes:
      - ./volumes/kibana-data:/usr/share/kibana/data
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - prod_server

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    ports:
      - "5044:5044"  # For beats (optional)
      - "5000:5000"  # TCP input
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #logstash 설정파일
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro  # <-- 이 줄 추가!
      - ../../logs:/logs #로그 볼륨
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - prod_server


networks:
  prod_server:
    external: true

#도커 자체 볼륨을 사용할떄 선언해야 함
#volumes:
#  volumes:
